neo4j:
  image: neo4j:3.2.6
  ports:
    - "7474:7474"
    - "7687:7687"
  environment:
    NEO4J_AUTH: neo4j/test
    NEO4J_dbms_memory_pagecache_size: 1G
    NEO4J_dbms_memory_heap_max__size: 2G
  volumes:
    - ./data:/data